name: Hello actions 0
on: [push]
jobs: 
  Hello-Job-1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Execucao do meu primeiro job"
      - run: echo "Varios comandos"

  Hello-Job-2:
    runs-on: ubuntu-latest
    needs: Hello-Job-1
    steps: 
      - run: echo "Outro job"
